server {
    listen 80;
    server_name localhost;
    root /var/www/html/pub;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location /static/ {
        expires max;
        add_header Cache-Control "public";
        try_files $uri $uri/ /static.php?resource=$uri&$args;
    }
    
    location ~ ^/static/version {
        rewrite ^/static/(version[^/]+/)?(.*)$ /static/$2 last;
    }

    location /media/ {
        try_files $uri $uri/ /get.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~* /\.(?!well-known) {
        deny all;
    }
}
